/*------------------------------------------------------------------------
File        : nature2contrat.i
Purpose     : Variables préprocesseur des nature de contrat
Author(s)   : Kantena - 2016/09/12
Notes       :
------------------------------------------------------------------------*/

&GLOBAL-DEFINE NATURECONTRAT-usageCommercial1953          "03003"
&GLOBAL-DEFINE NATURECONTRAT-usageCommercial-2ans         "03004"
&GLOBAL-DEFINE NATURECONTRAT-usageCommercialAccessoire    "03005"
&GLOBAL-DEFINE NATURECONTRAT-usageMixte1989Art17a         "03006"
&GLOBAL-DEFINE NATURECONTRAT-usageMixte1989Art17b         "03007"
&GLOBAL-DEFINE NATURECONTRAT-usageMixte1989Art11          "03008"
&GLOBAL-DEFINE NATURECONTRAT-usageMixte1948               "03009"
&GLOBAL-DEFINE NATURECONTRAT-usageMixte1982               "03010"
&GLOBAL-DEFINE NATURECONTRAT-usageMixteMehaignerie        "03011"
&GLOBAL-DEFINE NATURECONTRAT-usageProfessionnel1948       "03012"
&GLOBAL-DEFINE NATURECONTRAT-usageProfessionnel1986       "03013"
&GLOBAL-DEFINE NATURECONTRAT-usageProfessionnel1989       "03014"
&GLOBAL-DEFINE NATURECONTRAT-bauxRuraux                   "03015"
&GLOBAL-DEFINE NATURECONTRAT-usageLocationBureau          "03017"
&GLOBAL-DEFINE NATURECONTRAT-locationIsolee               "03022"
&GLOBAL-DEFINE NATURECONTRAT-contratLocation              "03023"
&GLOBAL-DEFINE NATURECONTRAT-habitationLoyerLibre         "03025"
&GLOBAL-DEFINE NATURECONTRAT-mandatAvecIndivision         "03030"
&GLOBAL-DEFINE NATURECONTRAT-mandatSansIndivision         "03031"
&GLOBAL-DEFINE NATURECONTRAT-usageMixteDroitCommun        "03056"
&GLOBAL-DEFINE NATURECONTRAT-salarieCopropriete           "03058"
&GLOBAL-DEFINE NATURECONTRAT-salarieGerance               "03059"
&GLOBAL-DEFINE NATURECONTRAT-chargeLocative               "03070"
&GLOBAL-DEFINE NATURECONTRAT-chargeChauffage              "03071"
&GLOBAL-DEFINE NATURECONTRAT-usageEmplacementPublicitaire "03072"
&GLOBAL-DEFINE NATURECONTRAT-mandatGestionRevenusGarantis "03074"
&GLOBAL-DEFINE NATURECONTRAT-mandatLocation               "03075"
&GLOBAL-DEFINE NATURECONTRAT-mandatSousLocation           "03076"
&GLOBAL-DEFINE NATURECONTRAT-residenceLocataire           "03077"
&GLOBAL-DEFINE NATURECONTRAT-AFUL                         "03078"
&GLOBAL-DEFINE NATURECONTRAT-ASL                          "03079"
&GLOBAL-DEFINE NATURECONTRAT-habitationVacant             "03080"
&GLOBAL-DEFINE NATURECONTRAT-commercialVacant             "03081"
&GLOBAL-DEFINE NATURECONTRAT-Leasing                      "03084"
&GLOBAL-DEFINE NATURECONTRAT-mandatLocationDelegue        "03085"
&GLOBAL-DEFINE NATURECONTRAT-mandatSousLocationDelegue    "03086"
&GLOBAL-DEFINE NATURECONTRAT-mandatLocationIndivision     "03093"
&GLOBAL-DEFINE NATURECONTRAT-specialVacant                "03094"
&GLOBAL-DEFINE NATURECONTRAT-restaurantInterEntreprise    "03105"
&GLOBAL-DEFINE NATURECONTRAT-recurrent                    "03107"
