/*------------------------------------------------------------------------
File        : type2role.i
Purpose     : Variables préprocesseur des type de rôle
Author(s)   : Kantena - 2016/09/12
Notes       : attention, certains codes dans type intervention!
derniere revue: 2018/06/01 - phm: OK
        mais traiter 00046, 00074
------------------------------------------------------------------------*/
&GLOBAL-DEFINE TYPEROLE-architecte                 "00002"
&GLOBAL-DEFINE TYPEROLE-compagnie                  "00003"
&GLOBAL-DEFINE TYPEROLE-beneficiaire               "00006"
&GLOBAL-DEFINE TYPEROLE-centrePerceptionImmeuble   "00007"
&GLOBAL-DEFINE TYPEROLE-coproprietaire             "00008"
&GLOBAL-DEFINE TYPEROLE-courtier                   "00009"
&GLOBAL-DEFINE TYPEROLE-fournisseur                "00012"
&GLOBAL-DEFINE TYPEROLE-garant                     "00013"
&GLOBAL-DEFINE TYPEROLE-mandataire                 "00014"
&GLOBAL-DEFINE TYPEROLE-Huissier                   "00015"
&GLOBAL-DEFINE TYPEROLE-coIndivisaire              "00016"
&GLOBAL-DEFINE TYPEROLE-notaire                    "00017"
&GLOBAL-DEFINE TYPEROLE-nuProprietaire             "00018"
&GLOBAL-DEFINE TYPEROLE-locataire                  "00019"
&GLOBAL-DEFINE TYPEROLE-mandant                    "00022"
&GLOBAL-DEFINE TYPEROLE-syndic2copro               "00027"
&GLOBAL-DEFINE TYPEROLE-usufruitier                "00029"
&GLOBAL-DEFINE TYPEROLE-promoteur                  "00030"
&GLOBAL-DEFINE TYPEROLE-centreAssiettes            "00031"
&GLOBAL-DEFINE TYPEROLE-centreImpots               "00032"
&GLOBAL-DEFINE TYPEROLE-centreRecettes             "00033"
&GLOBAL-DEFINE TYPEROLE-syndicat2copro             "00034"
&GLOBAL-DEFINE TYPEROLE-presidentConseilSyndical   "00035"
&GLOBAL-DEFINE TYPEROLE-membreConseilSyndical      "00036"
&GLOBAL-DEFINE TYPEROLE-Syndicexterne              "00037"
&GLOBAL-DEFINE TYPEROLE-prefecture                 "00038"
&GLOBAL-DEFINE TYPEROLE-mutuelleCaution            "00039"
&GLOBAL-DEFINE TYPEROLE-syndicatProfessionnel      "00040"
&GLOBAL-DEFINE TYPEROLE-vendeur                    "00041"
&GLOBAL-DEFINE TYPEROLE-acheteur                   "00042"
&GLOBAL-DEFINE TYPEROLE-entrepreneur               "00043"
&GLOBAL-DEFINE TYPEROLE-cabinet                    "00044"
&GLOBAL-DEFINE TYPEROLE-00046                      "00046"
&GLOBAL-DEFINE TYPEROLE-gestionnaire               "00047"
&GLOBAL-DEFINE TYPEROLE-agenceGestion              "00048"
&GLOBAL-DEFINE TYPEROLE-salarie                    "00050"
&GLOBAL-DEFINE TYPEROLE-colocataire                "00051"
&GLOBAL-DEFINE TYPEROLE-adjointConseilSyndical     "00052"
&GLOBAL-DEFINE TYPEROLE-bienfaiteurConseilSyndical "00053"
&GLOBAL-DEFINE TYPEROLE-respTravauxConseilSyndical "00054"
&GLOBAL-DEFINE TYPEROLE-benevole                   "00055"
&GLOBAL-DEFINE TYPEROLE-responsableSecurite        "00056"
&GLOBAL-DEFINE TYPEROLE-responsableComptabilite    "00057"
&GLOBAL-DEFINE TYPEROLE-coPresident                "00058"
&GLOBAL-DEFINE TYPEROLE-bailleur                   "00059"
&GLOBAL-DEFINE TYPEROLE-directeurAgence            "00060"
&GLOBAL-DEFINE TYPEROLE-coUsufruitier              "00065"
&GLOBAL-DEFINE TYPEROLE-coNuProprietaire           "00066"
&GLOBAL-DEFINE TYPEROLE-GardienBordereauCrg        "00067"
&GLOBAL-DEFINE TYPEROLE-candidatLocataire          "00069"
&GLOBAL-DEFINE TYPEROLE-prospect                   "00070"
&GLOBAL-DEFINE TYPEROLE-gerant                     "00071"
&GLOBAL-DEFINE TYPEROLE-00074                      "00074"
&GLOBAL-DEFINE TYPEROLE-centreSIE                  "00075"
&GLOBAL-DEFINE TYPEROLE-societeActionnaires        "00077"
&GLOBAL-DEFINE TYPEROLE-gardienExterne             "00080"
&GLOBAL-DEFINE TYPEROLE-agenceDelegataire          "00081"
&GLOBAL-DEFINE TYPEROLE-commercial                 "00082"
&GLOBAL-DEFINE TYPEROLE-responsableCommercial      "00083"
&GLOBAL-DEFINE TYPEROLE-tiersApporteur             "00084"
&GLOBAL-DEFINE TYPEROLE-salariePegase              "00150"
&GLOBAL-DEFINE TYPEROLE-tiers                      "99999"

&GLOBAL-DEFINE TYPEROLE-salarieComptaEI            50
