/*------------------------------------------------------------------------
File        : type2contrat.i
Purpose     : Variables préprocesseur des type de contrat
Author(s)   : Kantena - 2016/09/12
Notes       :
derniere revue: 2018/06/01 - phm: OK
        mais traiter 01081
------------------------------------------------------------------------*/
&GLOBAL-DEFINE TYPECONTRAT-Association              "01002"
&GLOBAL-DEFINE TYPECONTRAT-mandat2Syndic            "01003"
&GLOBAL-DEFINE TYPECONTRAT-titre2copro              "01004"
&GLOBAL-DEFINE TYPECONTRAT-mutation                 "01005"
&GLOBAL-DEFINE TYPECONTRAT-travaux                  "01006"
&GLOBAL-DEFINE TYPECONTRAT-GarantieLoyer            "01007"
&GLOBAL-DEFINE TYPECONTRAT-budget                   "01008"
&GLOBAL-DEFINE TYPECONTRAT-TaxeSurBureau            "01011"
&GLOBAL-DEFINE TYPECONTRAT-GarantieRisqueLocatif    "01013"
&GLOBAL-DEFINE TYPECONTRAT-ProtectionJuridique      "01017"
&GLOBAL-DEFINE TYPECONTRAT-ProprietaireNonOccupant  "01018"
&GLOBAL-DEFINE TYPECONTRAT-GarantiePierre           "01020"
&GLOBAL-DEFINE TYPECONTRAT-DerniereGarantieSpeciale "01029"
&GLOBAL-DEFINE TYPECONTRAT-mandat2Gerance           "01030"
&GLOBAL-DEFINE TYPECONTRAT-preBail                  "01032"
&GLOBAL-DEFINE TYPECONTRAT-bail                     "01033"
&GLOBAL-DEFINE TYPECONTRAT-acte2propriete           "01035"
&GLOBAL-DEFINE TYPECONTRAT-construction             "01036"
&GLOBAL-DEFINE TYPECONTRAT-prive                    "01038"
&GLOBAL-DEFINE TYPECONTRAT-assuranceGerance         "01039"
&GLOBAL-DEFINE TYPECONTRAT-CarteProfessionnelle     "01040"
&GLOBAL-DEFINE TYPECONTRAT-GarantieFinanciere       "01041"
&GLOBAL-DEFINE TYPECONTRAT-AdhesionFedeSyndicPro    "01042"
&GLOBAL-DEFINE TYPECONTRAT-assuranceSyndic          "01044"
&GLOBAL-DEFINE TYPECONTRAT-Salarie                  "01045"
&GLOBAL-DEFINE TYPECONTRAT-TVAIntracommunautaire    "01047"
&GLOBAL-DEFINE TYPECONTRAT-prestations              "01048"
&GLOBAL-DEFINE TYPECONTRAT-serviceGestion           "01049"
&GLOBAL-DEFINE TYPECONTRAT-assuranceLocative        "01050"
&GLOBAL-DEFINE TYPECONTRAT-DossierMutation          "01051"
&GLOBAL-DEFINE TYPECONTRAT-sepa                     "01052"
&GLOBAL-DEFINE TYPECONTRAT-fournisseur              "01059"
&GLOBAL-DEFINE TYPECONTRAT-UsufruitNuePropriete     "01075"
&GLOBAL-DEFINE TYPECONTRAT-CessionUsufruit          "01076"
&GLOBAL-DEFINE TYPECONTRAT-CessionNuePropriete      "01077"
&GLOBAL-DEFINE TYPECONTRAT-ExtinctionUsufruit       "01079"
&GLOBAL-DEFINE TYPECONTRAT-01081                    "01081"
&GLOBAL-DEFINE TYPECONTRAT-VacanceLocative          "01087"
&GLOBAL-DEFINE TYPECONTRAT-blocNote                 "01093"
&GLOBAL-DEFINE TYPECONTRAT-MandatLocation           "01094"
&GLOBAL-DEFINE TYPECONTRAT-societe                  "01096"
&GLOBAL-DEFINE TYPECONTRAT-mutationGerance          "01098"
&GLOBAL-DEFINE TYPECONTRAT-SalariePegase            "01145"
