/*------------------------------------------------------------------------
File        : ligneEcriture.i
Purpose     :
Author(s)   : kantena - 2017/05/02
Notes       :
derniere revue: 2018/07/28 - phm: OK
----------------------------------------------------------------------*/

&if defined(nomTable)   = 0 &then &scoped-define nomTable ttLigneEcriture
&endif
&if defined(serialName) = 0 &then &scoped-define serialName {&nomTable}
&endif
define temp-table {&nomTable} no-undo serialize-name '{&serialName}'
    field iNumeroAffaire             as integer    initial ?            label 'affair-num'
    field lAnalytique                as logical    initial ?            label 'lAnalytique' 
    field cAncienneLettre            as character  initial ?            label 'anclettre' 
    field cAppel                     as character  initial ?            label 'appel-num'
    field cAppelRegroupe             as character  initial ?            label 'appel-rgrp'
    field cCmtHono                   as character  initial ?            label 'cmthono'
    field cRegroupement              as character  initial ?            label 'coll-cle'
    field cCompte                    as character  initial ?            label 'cpt-cd'
    field cSousCompte                as character  initial ?            label 'cSousCompte'
    field cLibelleCompte             as character  initial ?            label 'cLibelleCompte'
    field daDateAffaire              as date                            label 'daaff'
    field daDateComptabilisation     as date                            label 'dacompta'
    field daDateDossier              as date                            label 'dadoss'
    field daDateEcheance             as date                            label 'daech'
    field daDateLettrage             as date                            label 'dalettrage'
    field daDateEcriture             as date                            label 'datecr'
    field cCodeDevise                as character  initial ?            label 'dev-cd'
    field cCodeDeviseEtrangere       as character  initial ?            label 'devetr-cd'
    field cLienJournal               as character  initial ?            label 'ecrln-jou-cd'
    field iLienNumeroLigne           as integer    initial ?            label 'ecrlc-lig'
    field cLienNumeroPiece           as integer    initial ?            label 'ecrln-piece-int'
    field cLienExercice              as integer    initial ?            label 'ecrln-prd-cd'
    field cLienNumeroPeriode         as integer    initial ?            label 'ecrln-prd-num'
    field iCodeEtablissement         as integer    initial ?            label 'etab-cd'
    field lAnalytique100             as logical    initial ?            label 'fg-ana100'
    field lLigneEquilibre            as logical    initial ?            label 'fg-eq'
    field lVentilationManuel         as logical    initial ?            label 'fg-man'
    field lProrata                   as logical    initial ?            label 'fg-prorata'
    field lReactivation              as logical    initial ?            label 'fg-reac'
    field lRegularise                as logical    initial ?            label 'fg-reg'
    field lComptabilisationSCI       as logical    initial ?            label 'fg-sci'
    field lEcritureLettree           as logical    initial ?            label 'flag-lettre'
    field cCompteTiersFournisseur    as character  initial ?            label 'fourn-cpt-cd'
    field cCollectifTiersFournisseur as character  initial ?            label 'fourn-sscoll-cle'
    field iIdentifiantFichier        as int64      initial ?            label 'id-fich'
    field cCodeJournal               as character  initial ?            label 'jou-cd'
    field cLettre                    as character  initial ?            label 'lettre'
    field cLibelle                   as character  initial ?            label 'lib'
    field cLibelleEcriture           as character  initial ?            label 'lib-ecr'
    field cLienADB                   as character  initial ?            label 'lien-adb'
    field iLienLigne                 as integer    initial ?            label 'lien-lig'
    field iNumeroLigne               as integer    initial ?            label 'lig'
    field iMandatJournalBanque       as integer    initial ?            label 'mandat-cd'
    field iExerciceMandatGlobal      as integer    initial ?            label 'mandat-prd-cd'
    field iPeriodeMandatGlobal       as integer    initial ?            label 'mandat-prd-num'
    field iMoisComptabilisation      as integer    initial ?            label 'moiscpt'
    field dMontantDebit              as decimal    initial ? decimals 2 label 'dMontantDebit'
    field dMontantCredit             as decimal    initial ? decimals 2 label 'dMontantCredit'
    field dMontant                   as decimal    initial ? decimals 2 label 'mt'
    field dMontantEURO               as decimal    initial ? decimals 2 label 'mt-EURO'
    field dMontantDevise             as decimal    initial ? decimals 2 label 'mtdev'
    field dMontantInitial            as decimal    initial ? decimals 2 label 'mtinit'
    field dMontantInitialEURO        as decimal    initial ? decimals 2 label 'mtinit-EURO'
    field dMontantReglement          as decimal    initial ? decimals 2 label 'mtreg'
    field dMontantReglement-EURO     as decimal    initial ? decimals 2 label 'mtreg-EURO'
    field dMontantTVA                as decimal    initial ? decimals 2 label 'mttva'
    field dMontantTVADevise          as decimal    initial ? decimals 2 label 'mttva-dev'
    field dMontantTVAEURO            as decimal    initial ? decimals 2 label 'mttva-EURO'
    field iCodeNatureScenario        as integer    initial ?            label 'natscen-cd'
    field iNumeroExercice            as integer    initial ?            label 'noexo'
    field iNumeroCRG                 as integer    initial ?            label 'num-crg' 
    field lPaieRegl                  as logical    initial ?            label 'paie-regl'
    field iNumeroPieceInterne        as integer    initial ?            label 'piece-int' 
    field iCodePeriode               as integer    initial ?            label 'prd-cd' 
    field iNumeroPeriode             as integer    initial ?            label 'prd-num' 
    field iCodeProfil                as integer    initial ?            label 'profil-cd' 
    field cReference                 as character  initial ?            label 'ref-num' 
    field iCodeReglement             as integer    initial ?            label 'regl-cd' 
    field cCodeRepartition           as character  initial ?            label 'repart-ana' 
    field lDebit                     as logical    initial ?            label 'sens' 
    field iCodeSociete               as integer    initial ?            label 'soc-cd' 
    field cCollectif                 as character  initial ?            label 'sscoll-cle'
    field iStatutTransfertSCI        as integer    initial ?            label 'statut' 
    field dTaux                      as decimal    initial ? decimals 8 label 'taux'
    field iCodeTaxe                  as integer    initial ?            label 'taxe-cd' 
    field iCodeTaxeInitial           as integer    initial ?            label 'taxeinit'
    field iTotalDetail               as integer    initial ?            label 'tot-det' 
    field lTvaEncaissementDebit      as logical    initial ?            label 'tva-enc-deb'
    field cTypeMouvement             as character  initial ?            label 'type-cle' 
    field iTypeEcriture              as integer    initial ?            label 'type-ecr' 
    field cZone1                     as character  initial ?            label 'Zone1' 
    field cZone2                     as character  initial ?            label 'Zone2'
    field cZone3                     as character  initial ?            label 'Zone3'

    field CRUD        as character
    field dtTimestamp as datetime
    field rRowid      as rowid
.
