/*------------------------------------------------------------------------
File        : ligneEcritureAnalytique.i
Purpose     :
Author(s)   : kantena - 2017/05/02
Notes       : le plus grans entier 32 bits est exp(2, 31) - 1 = 2147483647
derniere revue: 2018/08/09 - phm: OK
----------------------------------------------------------------------*/
&if defined(nomTable)   = 0 &then &scoped-define nomTable ttLigneEcritureAnalytique
&endif
&if defined(serialName) = 0 &then &scoped-define serialName {&nomTable}
&endif
define temp-table {&nomTable} no-undo serialize-name '{&serialName}'
    field iNumeroAffaire         as integer    initial ?            label 'affair-num'
    field cCodeAna               as character  initial ?            label 'ana-cd'
    field cCodeRubrique          as character  initial ?            label 'ana1-cd'
    field cLibelleRubrique       as character  initial ?            label 'cLibelleRubrique'
    field cCodeSousRubrique      as character  initial ?            label 'ana2-cd'
    field cLibelleSousRubrique   as character  initial ?            label 'cLibelleSousRubrique'
    field cCodeFiscal            as character  initial ?            label 'ana3-cd'
    field cLibelleFiscal         as character  initial ?            label 'cLibelleFiscal'
    field cCodeCle               as character  initial ?            label 'ana4-cd'
    field cLibelleCle            as character  initial ?            label 'cLibelleCle'
    field lAnalytique100         as logical    initial ?            label 'analytique'
    field cAnnulRefNum           as character  initial ?            label 'annul-ref-num'
    field iCodeBudget            as integer    initial ?            label 'budg-cd'
    field cCodeUnite             as character  initial ?            label 'cdunite'
    field cmthono                as character  initial ?            label 'cmthono'
    field cCompte                as character  initial ?            label 'cpt-cd'
    field cSousCompte            as character  initial ?            label 'cSousCompte'
    field cLibelleCompte         as character  initial ?            label 'cLibelleCompte'
    field cptgen                 as character  initial ?            label 'cptgen'
    field daDateComptabilisation as date       initial ?            label 'dacompta'
    field daDateCreation         as date       initial ?            label 'dacrea'
    field daDateModification     as date       initial ?            label 'damod'
    field daDateEcriture         as date       initial ?            label 'datecr'
    field cCodeDevise            as character  initial ?            label 'dev-cd'
    field cCodeDeviseEtrangere   as character  initial ?            label 'devetr-cd'
    field cCodeDivers            as integer    initial ?            label 'divers-cd'
    field cNumeroDossier         as character  initial ?            label 'doss-num'
    field iCodeEtablissement     as integer    initial ?            label 'etab-cd'
    field ihcrea                 as integer    initial ?            label 'ihcrea'
    field ihmod                  as integer    initial ?            label 'ihmod'
    field cCodeIRF               as character  initial ?            label 'irf-cd'
    field cCodeJournal           as character  initial ?            label 'jou-cd'
    field cLibelleDiv            as character  initial ?            label 'lbdiv'
    field cLibelleDiv2           as character  initial ?            label 'lbdiv2'
    field cLibelleDiv3           as character  initial ?            label 'lbdiv3'
    field cLibelleRegroupement   as character  initial ?            label 'librgt'
    field cLibelle               as character  initial ?            label 'lib'
    field cLibelleEcriture       as character  initial ?            label 'lib-ecr'
    field iNumeroLigne           as integer    initial ?            label 'lig'
    field dMontantDebit          as decimal    initial ? decimals 2 label 'dMontantDebit'
    field dMontantCredit         as decimal    initial ? decimals 2 label 'dMontantCredit'
    field dMontant               as decimal    initial ? decimals 2 label 'mt'
    field dMontantEURO           as decimal    initial ? decimals 2 label 'mt-EURO'
    field dMontantDevis          as decimal    initial ? decimals 2 label 'mtdev'
    field dMontantTVA            as decimal    initial ? decimals 2 label 'mttva'
    field dMontantTVADevise      as decimal    initial ? decimals 2 label 'mttva-dev'
    field dMontantTVAEURO        as decimal    initial ? decimals 2 label 'mttva-EURO'
    field iNumeroExercice        as integer    initial ?            label 'noexo'
    field iNumeroImmeuble        as integer    initial ?            label 'noimm'
    field iNumeroLot             as integer    initial ?            label 'nolot'
    field iNumeroCRG             as integer    initial ?            label 'num-crg'
    field iNumeroPieceInterne    as integer    initial ?            label 'piece-int'
    field iPosition              as integer    initial ?            label 'pos'
    field dPourcentage           as decimal    initial ? decimals 2 label 'pourc'
    field iCodePeriode           as integer    initial ?            label 'prd-cd'
    field iNumeroPeriode         as integer    initial ?            label 'prd-num'
    field pointLivraison         as character  initial ?            label 'ptlivr'
    field dQuantite              as decimal    initial ? decimals 2 label 'qte'
    field cRegroupement          as character  initial ?            label 'regrp'
    field cRegroupementDepense   as character  initial ?            label 'regrp-dep'
    field cRegroupementIRF       as character  initial ?            label 'regrp-irf'
    field cRepartitionAna        as character  initial ?            label 'repart-ana'
    field cCodeReport            as integer    initial ?            label 'report-cd'
    field lDebit                 as logical    initial ?            label 'sens'
    field iCodeSociete           as integer    initial ?            label 'soc-cd'
    field cCollectif             as character  initial ?            label 'sscoll-cle'
    field iTantieme              as integer    initial ?            label 'tantieme'
    field dTauxCle               as decimal    initial ? decimals 2 label 'taux-cle'
    field iCodeTaxe              as integer    initial ?            label 'taxe-cd'
    field iCodeTravaux           as integer    initial ?            label 'travaux-cd'
    field iCodeTVA               as integer    initial ?            label 'tva-cd'
    field dTauxRecuperationTva   as decimal    initial ? decimals 2 label 'tx-recuptva'
    field cTypeCle               as character  initial ?            label 'type-cle'
    field lTypeVentil            as logical    initial ?            label 'typeventil'
    field usrid                  as character  initial ?            label 'usrid'
    field usridmod               as character  initial ?            label 'usridmod'
    field dtTimestamp            as datetime
    field CRUD                   as character
    field rRowid                 as rowid
.