/*------------------------------------------------------------------------
File        : fusionOrganismesocial.cls
Purpose     : Classe des champs fusion utilisateur ORGANISMESOCIAL
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
block-level on error undo, throw.
class bureautique.fusion.classe.fusionOrganismesocial:
    /*------------------------------------------------------------------------------
    purpose:
    Notes  :
    ------------------------------------------------------------------------------*/
    define public property TitreCaF                   as character no-undo get. set.
    define public property TitreLCaF                  as character no-undo get. set.
    define public property NomCaF                     as character no-undo get. set.
    define public property adresseCaF                 as character no-undo get. set.
    define public property SuiteadresseCaF            as character no-undo get. set.
    define public property CodePostalCaF              as character no-undo get. set.
    define public property VilleCaF                   as character no-undo get. set.
    define public property TitreCentrePaiement        as character no-undo get. set.
    define public property TitreLCentrePaiement       as character no-undo get. set.
    define public property NomCentrePaiement          as character no-undo get. set.
    define public property adresseCentrePaiement      as character no-undo get. set.
    define public property SuiteadresseCentrePaiement as character no-undo get. set.
    define public property CodePostalCentrePaiement   as character no-undo get. set.
    define public property VilleCentrePaiement        as character no-undo get. set.
    define public property TitreCentreRecette         as character no-undo get. set.
    define public property TitreLCentreRecette        as character no-undo get. set.
    define public property NomCentreRecette           as character no-undo get. set.
    define public property adresseCentreRecette       as character no-undo get. set.
    define public property SuiteadresseCentreRecette  as character no-undo get. set.
    define public property CodePostalCentreRecette    as character no-undo get. set.
    define public property VilleCentreRecette         as character no-undo get. set.
    define public property TitreaSSeDIC               as character no-undo get. set.
    define public property TitreLaSSeDIC              as character no-undo get. set.
    define public property NomaSSeDIC                 as character no-undo get. set.
    define public property adresseaSSeDIC             as character no-undo get. set.
    define public property SuiteadresseaSSeDIC        as character no-undo get. set.
    define public property CodePostalaSSeDIC          as character no-undo get. set.
    define public property VilleaSSeDIC               as character no-undo get. set.
    define public property adresseCentreImpot         as character no-undo get. set.
    define public property SuiteadresseCentreImpot    as character no-undo get. set.
    define public property CodePostalCentreImpot      as character no-undo get. set.
    define public property VilleCentreImpot           as character no-undo get. set.
    define public property NomCentreImpot             as character no-undo get. set.
    define public property TelephoneCentreImpot       as character no-undo get. set.
    define public property VilleCedexCaF              as character no-undo get. set.
    define public property VilleCedexCentrePaiement   as character no-undo get. set.
    define public property VilleCedexCentreRecette    as character no-undo get. set.
    define public property VilleCedexaSSeDIC          as character no-undo get. set.
    define public property VilleCedexacheteurDoMut    as character no-undo get. set.
end class.
