/*------------------------------------------------------------------------
File        : fusionSyndic.cls
Purpose     : Classe des champs fusion utilisateur SYNDIC
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
block-level on error undo, throw.
class bureautique.fusion.classe.fusionSyndic:
    /*------------------------------------------------------------------------------
    purpose:
    Notes  :
    ------------------------------------------------------------------------------*/
    define public property CiviliteSyndCopro                 as character no-undo get. set.
    define public property TitreSyndCopro                    as character no-undo get. set.
    define public property TitreLSyndCopro                   as character no-undo get. set.
    define public property NomSyndCopro                      as character no-undo get. set.
    define public property adresseSyndCopro                  as character no-undo get. set.
    define public property SuiteadresseSyndCopro             as character no-undo get. set.
    define public property CodePostalSyndCopro               as character no-undo get. set.
    define public property VilleSyndCopro                    as character no-undo get. set.
    define public property TelSyndCopro                      as character no-undo get. set.
    define public property NumSyndCopro                      as character no-undo get. set.
    define public property NumRegSyn                         as character no-undo get. set.
    define public property DateSigSyn                        as character no-undo get. set.
    define public property LieSigSyn                         as character no-undo get. set.
    define public property DateDebSyn                        as character no-undo get. set.
    define public property DateFinSyn                        as character no-undo get. set.
    define public property DureeSyn                          as character no-undo get. set.
    define public property DelaiSyn                          as character no-undo get. set.
    define public property DateResiliationSyn                as character no-undo get. set.
    define public property MotifResiliationSyn               as character no-undo get. set.
    define public property Tantieme                          as character no-undo get. set.
    define public property TitrePresident                    as character no-undo get. set.
    define public property TitreLPresident                   as character no-undo get. set.
    define public property NomPresident                      as character no-undo get. set.
    define public property NomPresidentSeul                  as character no-undo get. set.
    define public property PrenomPresidentSeul               as character no-undo get. set.
    define public property adressePresident                  as character no-undo get. set.
    define public property SuiteadressePresident             as character no-undo get. set.
    define public property CodePostalPresident               as character no-undo get. set.
    define public property VillePresident                    as character no-undo get. set.
    define public property TelephonePresident                as character no-undo get. set.
    define public property NomGestionnaireCopro              as character no-undo get. set.
    define public property NumPresident                      as character no-undo get. set.
    define public property TitreDirecteuragenceCopro         as character no-undo get. set.
    define public property TitreLDirecteuragenceCopro        as character no-undo get. set.
    define public property NomDirecteuragenceCopro           as character no-undo get. set.
    define public property NomagenceCopro                    as character no-undo get. set.
    define public property adresseagenceCorpo                as character no-undo get. set.
    define public property SuiteadresseagenceCopro           as character no-undo get. set.
    define public property CodePostalagenceCopro             as character no-undo get. set.
    define public property VilleagenceCopro                  as character no-undo get. set.
    define public property Tel1agenceCopro                   as character no-undo get. set.
    define public property DatelDebSyn                       as character no-undo get. set.
    define public property DateDebSynLettre                  as character no-undo get. set.
    define public property DatelSigSyn                       as character no-undo get. set.
    define public property DateSigSynLettre                  as character no-undo get. set.
    define public property DatelFinSyn                       as character no-undo get. set.
    define public property DateFinSynLettre                  as character no-undo get. set.
    define public property DatelResiliationSyn               as character no-undo get. set.
    define public property DateResiliationSynLettre          as character no-undo get. set.
    define public property TelGestionnaireCopro              as character no-undo get. set.
    define public property FaxGestionnaireCopro              as character no-undo get. set.
    define public property PaysCoproprietaire                as character no-undo get. set.
    define public property DateIniSyn                        as character no-undo get. set.
    define public property DateLIniSyn                       as character no-undo get. set.
    define public property DateIniSynenLettre                as character no-undo get. set.
    define public property PortablePresident                 as character no-undo get. set.
    define public property PortableGestionnaireCopro         as character no-undo get. set.
    define public property FaxPresident                      as character no-undo get. set.
    define public property emailPresident                    as character no-undo get. set.
    define public property emailGestionnaireCopro            as character no-undo get. set.
    define public property VilleCedexSyndCopro               as character no-undo get. set.
    define public property VilleCedexPresident               as character no-undo get. set.
    define public property VilleCedexagenceCopro             as character no-undo get. set.
    define public property NomCompletGestionnaireCopro       as character no-undo get. set.
    define public property BanqueSyndicat                    as character no-undo get. set.
    define public property NoCompteBancaireSyndicat          as character no-undo get. set.
    define public property TitulaireBanqueSyndicat           as character no-undo get. set.
    define public property NoBICSyndicat                     as character no-undo get. set.
    define public property FonctionGestionnaireCopro         as character no-undo get. set.
    define public property ComplementAdresseIdentSyndCopro   as character no-undo get. set.
    define public property ComplementAdresseIdentPresident   as character no-undo get. set.
    define public property ComplementAdresseIdentAgenceCopro as character no-undo get. set.
    define public property NoMandat                          as character no-undo get. set.
end class.
