/*------------------------------------------------------------------------
File        : fusionContratfour.cls
Purpose     : Classe des champs fusion utilisateur CONTRATFOUR
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
block-level on error undo, throw.
class bureautique.fusion.classe.fusionContratfour:
    /*------------------------------------------------------------------------------
    purpose:
    Notes  :
    ------------------------------------------------------------------------------*/
    define public property NumCttFournisseur              as character no-undo get. set.
    define public property RegCttFournisseur              as character no-undo get. set.
    define public property DateSigCttFournisseur          as character no-undo get. set.
    define public property DateeffetCttFournisseur        as character no-undo get. set.
    define public property DureeCttFournisseur            as character no-undo get. set.
    define public property DateFinCttFournisseur          as character no-undo get. set.
    define public property PreavisCttFournisseur          as character no-undo get. set.
    define public property PeriodiciteCttFournisseur      as character no-undo get. set.
    define public property MtComptaCttFournisseur         as character no-undo get. set.
    define public property MtContractuelCttFournisseur    as character no-undo get. set.
    define public property NumFourCttFournisseur          as character no-undo get. set.
    define public property TitreFourCttFournisseur        as character no-undo get. set.
    define public property TitreLFourCttFournisseur       as character no-undo get. set.
    define public property NomFourCttFournisseur          as character no-undo get. set.
    define public property adresseFourCttFournisseur      as character no-undo get. set.
    define public property SuiteadresseFourCttFournisseur as character no-undo get. set.
    define public property CodePostalFourCttFournisseur   as character no-undo get. set.
    define public property VilleFourCttFournisseur        as character no-undo get. set.
    define public property DatelSigCttFournisseur         as character no-undo get. set.
    define public property DateSigCttFournisseurLettre    as character no-undo get. set.
    define public property DateleffetCttFournisseur       as character no-undo get. set.
    define public property DateeffetCttFournisseurLettre  as character no-undo get. set.
    define public property DatelFinCttFournisseur         as character no-undo get. set.
    define public property DateFinCttFournisseurLettre    as character no-undo get. set.
    define public property VilleCedexCoproVendeur         as character no-undo get. set.
    define public property TelFourCttFournisseur          as character no-undo get. set.
    define public property emailFourCttFournisseur        as character no-undo get. set.
end class.
