/*------------------------------------------------------------------------
File        : fusionDestinataire.cls
Purpose     : Classe des champs fusion utilisateur DESTINATAIRE
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
block-level on error undo, throw.
class bureautique.fusion.classe.fusionDestinataire:
    /*------------------------------------------------------------------------------
    purpose:
    Notes  :
    ------------------------------------------------------------------------------*/
    define public property TitreLDestinataire           as character no-undo get. set.
    define public property NomDesContact                as character no-undo get. set.
    define public property TitreDesContact              as character no-undo get. set.
    define public property NomDestiSeul                 as character no-undo get. set.
    define public property PrenDestiSeul                as character no-undo get. set.
    define public property TelephoneDestinataire        as character no-undo get. set.
    define public property DateNaissanceDesti           as character no-undo get. set.
    define public property DateLNaissanceDesti          as character no-undo get. set.
    define public property NumDestinataire              as character no-undo get. set.
    define public property FaxDestinataire              as character no-undo get. set.
    define public property NomCompletDestinataire       as character no-undo get. set.
    define public property NomCompletDesContact         as character no-undo get. set.
    define public property NomCompletDesCo              as character no-undo get. set.
    define public property NomCompletDesRep             as character no-undo get. set.
    define public property FormeLgJuridDestinataire     as character no-undo get. set.
    define public property FormeCtJuridDestinataire     as character no-undo get. set.
    define public property PolitesseDestinataire        as character no-undo get. set.
    define public property PortableDestinataire         as character no-undo get. set.
    define public property PaysDestinataire             as character no-undo get. set.
    define public property emailDestinataire            as character no-undo get. set.
    define public property StatutPropriete              as character no-undo get. set.
    define public property BurDistDestinataire          as character no-undo get. set.
    define public property SIReNDestinataire            as character no-undo get. set.
    define public property NaFDestinataire              as character no-undo get. set.
    define public property VilleCedexDestinataire       as character no-undo get. set.
    define public property BanqueDestinataire           as character no-undo get. set.
    define public property TituRibDestinataire          as character no-undo get. set.
    define public property NoCompteBancaireDestinataire as character no-undo get. set.
    define public property NoBICDestinataire            as character no-undo get. set.
    define public property WebIdentifiantactivation     as character no-undo get. set.
    define public property WebMotDePasseactivation      as character no-undo get. set.
    define public property RUMDesti                     as character no-undo get. set.
    define public property DateSignatureRUMDesti        as character no-undo get. set.
    define public property DateDernUtilisationRUMDesti  as character no-undo get. set.
    define public property NomReclamPrelSePaDesti       as character no-undo get. set.
    define public property NomModifPrelSePaDesti        as character no-undo get. set.
    define public property NomCreancierDesti            as character no-undo get. set.
    define public property ICSCreancierDesti            as character no-undo get. set.
    define public property IBaNCreancierDesti           as character no-undo get. set.
    define public property BICCreancierDesti            as character no-undo get. set.
    define public property BanqueCreancierDesti         as character no-undo get. set.
    define public property DelaiNotifPrelSePaDesti      as character no-undo get. set.
    define public property DatePassagePrelSePaDesti     as character no-undo get. set.
    define public property LieuSignatureRUMDesti        as character no-undo get. set.
    define public property DatePreNotifRUMDesti         as character no-undo get. set.
    define public property DateecheanceRUMDesti         as character no-undo get. set.
    define public property MontantecheanceRUMDesti      as character no-undo get. set.
    define public property RoleDesti                    as character no-undo get. set.
    define public property adresseCreancierDesti        as character no-undo get. set.
    define public property SuiteadresseCreancierDesti   as character no-undo get. set.
    define public property CodePostalCreancierDesti     as character no-undo get. set.
    define public property VilleCreancierDesti          as character no-undo get. set.
    define public property VilleCedexCreancierDesti     as character no-undo get. set.
    define public property PaysCreancierDesti           as character no-undo get. set.
    define public property TitreDestinataire            as character no-undo get. set.
    define public property NomDestinataire              as character no-undo get. set.
    define public property adresseDestinataire          as character no-undo get. set.
    define public property SuiteadresseDestinataire     as character no-undo get. set.
    define public property CodePostalDestinataire       as character no-undo get. set.
    define public property VilleDestinataire            as character no-undo get. set.
    define public property ComplementAdresseIdentCreancierDesti as character no-undo get. set.
    define public property ComplementAdresseIdentDestinataire   as character no-undo get. set.
end class.
