/*------------------------------------------------------------------------
File        : fusionAccessoire.cls
Purpose     : Classe des champs fusion utilisateur ACCESSOIRE
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
block-level on error undo, throw.
class bureautique.fusion.classe.fusionAccessoire:
    /*------------------------------------------------------------------------------
    purpose:
    Notes  :
    ------------------------------------------------------------------------------*/
    define public property TypeaccessoireDomotique                     as character no-undo get. set.
    define public property NomFournisseuraccessoireDomotique           as character no-undo get. set.
    define public property adresseFournisseuraccessoireDomotique       as character no-undo get. set.
    define public property SuiteadresseFournisseuraccessoireDomotique  as character no-undo get. set.
    define public property CodePostalFournisseuraccessoireDomotique    as character no-undo get. set.
    define public property VilleFournisseuraccessoireDomotique         as character no-undo get. set.
    define public property NoLotaccessoireDomotique                    as character no-undo get. set.
    define public property NomDestinataireaccessoireDomotique          as character no-undo get. set.
    define public property adresseDestinataireaccessoireDomotique      as character no-undo get. set.
    define public property SuiteadresseDestinataireaccessoireDomotique as character no-undo get. set.
    define public property CodePostalDestinataireaccessoireDomotique   as character no-undo get. set.
    define public property VilleDestinataireaccessoireDomotique        as character no-undo get. set.
    define public property NumSerieaccessoireDomotique                 as character no-undo get. set.
    define public property MontantCautionaccessoireDomotique           as character no-undo get. set.
    define public property DateRemiseaccessoireDomotique               as character no-undo get. set.
    define public property DateRestitutionaccessoireDomotique          as character no-undo get. set.
    define public property CommentaireaccessoireDomotique              as character no-undo get. set.
    define public property BatimententreeescalierDomotique             as character no-undo get. set.
    define public property VilleCedexFournisseuraccessoireDomotique    as character no-undo get. set.
    define public property VilleCedexDestinataireaccessoireDomotique   as character no-undo get. set.
end class.
