/*------------------------------------------------------------------------
File        : fusionSignalement.cls
Purpose     : Classe des champs fusion utilisateur SIGNALEMENT
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
block-level on error undo, throw.
class bureautique.fusion.classe.fusionSignalement:
    /*------------------------------------------------------------------------------
    purpose:
    Notes  :
    ------------------------------------------------------------------------------*/
    define public property NumSignalement                   as character no-undo get. set.
    define public property DelaiSignalement                 as character no-undo get. set.
    define public property TableSignalement                 as character no-undo get. set.
    define public property TableComplInfo                   as character no-undo get. set.
    define public property ListeDesignationSignalement      as character no-undo get. set.
    define public property ListeRefarticleSignalement       as character no-undo get. set.
    define public property ListeQteSignalement              as character no-undo get. set.
    define public property ListeDelaiSignalement            as character no-undo get. set.
    define public property ListeCommentaireSignalement      as character no-undo get. set.
    define public property ListeCleSignalement              as character no-undo get. set.
    define public property ListeCleLibelleSignalement       as character no-undo get. set.
    define public property ListeLotsSignalement             as character no-undo get. set.
    define public property ListeNatureLotsSignalement       as character no-undo get. set.
    define public property ListeBatLotsSignalement          as character no-undo get. set.
    define public property ListeentreeLotsSignalement       as character no-undo get. set.
    define public property ListeescLotsSignalement          as character no-undo get. set.
    define public property ListeetageLotsSignalement        as character no-undo get. set.
    define public property ListePorteLotsSignalement        as character no-undo get. set.
    define public property ListeoccupantLotsSignalement     as character no-undo get. set.
    define public property TableLotsSignalement             as character no-undo get. set.
    define public property TableLotsoccupantsSignalement    as character no-undo get. set.
    define public property RoleSignalantSignalement         as character no-undo get. set.
    define public property TitreSignalantSignalement        as character no-undo get. set.
    define public property TitreLSignalantSignalement       as character no-undo get. set.
    define public property CiviliteSignalantSignalement     as character no-undo get. set.
    define public property NomSignalantSignalement          as character no-undo get. set.
    define public property NomCompletSignalantSignalement   as character no-undo get. set.
    define public property adresseSignalantSignalement      as character no-undo get. set.
    define public property SuiteadresseSignalantSignalement as character no-undo get. set.
    define public property CodePostalSignalantSignalement   as character no-undo get. set.
    define public property VilleSignalantSignalement        as character no-undo get. set.
    define public property VilleCedexSignalantSignalement   as character no-undo get. set.
    define public property ListeTeloccupantLotsSignalement  as character no-undo get. set.
    define public property TelSignalantSignalement          as character no-undo get. set.
    define public property PortableSignalantSignalement     as character no-undo get. set.
    define public property ListeRubartSignalement           as character no-undo get. set.
    define public property ListeSSRubartSignalement         as character no-undo get. set.
    define public property ListeCodeFiscartSignalement      as character no-undo get. set.
    define public property ListeRubartDevis                 as character no-undo get. set.
    define public property ListeSSRubartDevis               as character no-undo get. set.
    define public property ListeCodeFiscartDevis            as character no-undo get. set.
    define public property ListeRubartoS                    as character no-undo get. set.
    define public property ListeSSRubartoS                  as character no-undo get. set.
    define public property ListeCodeFiscartoS               as character no-undo get. set.
    define public property ListeemailoccupantSignalement    as character no-undo get. set.
end class.
