/*------------------------------------------------------------------------
File        : fusionTitrecopro.cls
Purpose     : Classe des champs fusion utilisateur TITRECOPRO
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
block-level on error undo, throw.
class bureautique.fusion.classe.fusionTitrecopro:
    /*------------------------------------------------------------------------------
    purpose:
    Notes  :
    ------------------------------------------------------------------------------*/
    define public property TitreCoproprietaire                     as character no-undo get. set.
    define public property TitreLCoproprietaire                    as character no-undo get. set.
    define public property NomCoproprietaire                       as character no-undo get. set.
    define public property adresseCoproprietaire                   as character no-undo get. set.
    define public property SuiteadresseCoproprietaire              as character no-undo get. set.
    define public property CodePostalCoproprietaire                as character no-undo get. set.
    define public property VilleCoproprietaire                     as character no-undo get. set.
    define public property TelCoproprietaire                       as character no-undo get. set.
    define public property NumCoproprietaire                       as character no-undo get. set.
    define public property SoldeCoproprietaire                     as character no-undo get. set.
    define public property SoldeCoproprietaireenLettre             as character no-undo get. set.
    define public property TantCleGene                             as character no-undo get. set.
    define public property DateSoldeCopro                          as character no-undo get. set.
    define public property DateLSoldeCopro                         as character no-undo get. set.
    define public property TitreCoproContact                       as character no-undo get. set.
    define public property NomCoproContact                         as character no-undo get. set.
    define public property LstLotCoprop                            as character no-undo get. set.
    define public property TituRibCoprop                           as character no-undo get. set.
    define public property NoCompteBancaireCopro                   as character no-undo get. set.
    define public property BanqueCopro                             as character no-undo get. set.
    define public property DateSoldeCoproLettre                    as character no-undo get. set.
    define public property NomCompletCoproprietaire                as character no-undo get. set.
    define public property NomCompletCoproContact                  as character no-undo get. set.
    define public property NomCompletCoproCo                       as character no-undo get. set.
    define public property NomCompletCoproRep                      as character no-undo get. set.
    define public property PolitesseCoproprietaire                 as character no-undo get. set.
    define public property PortableCoproprietaire                  as character no-undo get. set.
    define public property ListeLotsCoproprietaire                 as character no-undo get. set.
    define public property FaxCoproprietaire                       as character no-undo get. set.
    define public property emailCoproprietaire                     as character no-undo get. set.
    define public property VilleCedexCoproprietaire                as character no-undo get. set.
    define public property NoBICCoproprietaire                     as character no-undo get. set.
    define public property RUMCoproprietaire                       as character no-undo get. set.
    define public property DateSignatureRUMCoproprietaire          as character no-undo get. set.
    define public property DateDernUtilisationRUMCoproprietaire    as character no-undo get. set.
    define public property NomReclamPrelSePaCoproprietaire         as character no-undo get. set.
    define public property NomModifPrelSePaCoproprietaire          as character no-undo get. set.
    define public property NomCreancierCoproprietaire              as character no-undo get. set.
    define public property ICSCreancierCoproprietaire              as character no-undo get. set.
    define public property IBaNCreancierCoproprietaire             as character no-undo get. set.
    define public property BICCreancierCoproprietaire              as character no-undo get. set.
    define public property BanqueCreancierCoproprietaire           as character no-undo get. set.
    define public property DelaiNotifPrelSePaCoproprietaire        as character no-undo get. set.
    define public property DatePassagePrelSePaCoproprietaire       as character no-undo get. set.
    define public property LieuSignatureRUMCoproprietaire          as character no-undo get. set.
    define public property DatePreNotifRUMCoproprietaire           as character no-undo get. set.
    define public property DateecheanceRUMCoproprietaire           as character no-undo get. set.
    define public property MontantecheanceRUMCoproprietaire        as character no-undo get. set.
    define public property FgCopContentieux                        as character no-undo get. set.
    define public property DtDebutContentieuxCop                   as character no-undo get. set.
    define public property DtLDebutContentieuxCop                  as character no-undo get. set.
    define public property DtDebutContentieuxenLettreCop           as character no-undo get. set.
    define public property etat-contentieuxCop                     as character no-undo get. set.
    define public property Commentaire-ContentieuxCop              as character no-undo get. set.
    define public property SoldeCopro_CHB                          as character no-undo get. set.
    define public property SoldeCopro_CHB_enLettre                 as character no-undo get. set.
    define public property SoldeCopro_C_CHB                        as character no-undo get. set.
    define public property SoldeCopro_C_CHB_enLettre               as character no-undo get. set.
    define public property IndiceImpayesContentieuxCop             as character no-undo get. set.
    define public property DtDepIndiceContentieuxCop               as character no-undo get. set.
    define public property DtLDepIndiceContentieuxCop              as character no-undo get. set.
    define public property DtDepIndiceContentieuxCopenLettre       as character no-undo get. set.
    define public property DtDelivCommandContentieuxCop            as character no-undo get. set.
    define public property DtLDelivCommandContentieuxCop           as character no-undo get. set.
    define public property DtDelivCommandContentieuxCopenLettre    as character no-undo get. set.
    define public property DtDelivSignassignContentieuxCop         as character no-undo get. set.
    define public property DtLDelivSignassignContentieuxCop        as character no-undo get. set.
    define public property DtDelivSignassignContentieuxCopenLettre as character no-undo get. set.
    define public property DtaudienceContentieuxCop                as character no-undo get. set.
    define public property DtLaudienceContentieuxCop               as character no-undo get. set.
    define public property DtaudienceContentieuxCopenLettre        as character no-undo get. set.
end class.
