/*------------------------------------------------------------------------
File        : fusionOrdreservice.cls
Purpose     : Classe des champs fusion utilisateur ORDRESERVICE
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
block-level on error undo, throw.
class bureautique.fusion.classe.fusionOrdreservice:
    /*------------------------------------------------------------------------------
    purpose:
    Notes  :
    ------------------------------------------------------------------------------*/
    define public property AdresseSignalantoS                as character no-undo get. set.
    define public property CiviliteSignalantoS               as character no-undo get. set.
    define public property CodePostalSignalantoS             as character no-undo get. set.
    define public property Commentaire1OS                    as character no-undo get. set.
    define public property ComplementAdresseIdentSignalantOS as character no-undo get. set.
    define public property CondPaiemordreService             as character no-undo get. set.
    define public property CondPortordreService              as character no-undo get. set.
    define public property DateClotureOS                     as character no-undo get. set.
    define public property DateCreationordreServiceLettre    as character no-undo get. set.
    define public property DateCreationordreService          as character no-undo get. set.
    define public property DateDebutoS                       as character no-undo get. set.
    define public property DateFinoS                         as character no-undo get. set.
    define public property DateLCreationordreService         as character no-undo get. set.
    define public property HeureCreationOS                   as character no-undo get. set.
    define public property ListeBatLotsOS                    as character no-undo get. set.
    define public property ListeCleLibelleOS                 as character no-undo get. set.
    define public property ListeCleOS                        as character no-undo get. set.
    define public property ListeCodeFiscArtOs                as character no-undo get. set.
    define public property ListeDesignationOS                as character no-undo get. set.
    define public property ListeDomaiArtOS                   as character no-undo get. set.
    define public property ListeDtDebutOS                    as character no-undo get. set.
    define public property ListeDtFinOS                      as character no-undo get. set.
    define public property ListeCommentaireOS                as character no-undo get. set.
    define public property ListeEscLotsOS                    as character no-undo get. set.
    define public property ListeEmailOccupantOS              as character no-undo get. set.
    define public property ListeEtageLotsOS                  as character no-undo get. set.
    define public property ListeLibelleArtOS                 as character no-undo get. set.
    define public property ListeLotsoS                       as character no-undo get. set.
    define public property ListeMontantOS                    as character no-undo get. set.
    define public property ListMontantHToS                   as character no-undo get. set.
    define public property ListeNatureLotsoS                 as character no-undo get. set.
    define public property ListeentreeLotsoS                 as character no-undo get. set.
    define public property ListeoccupantLotsoS               as character no-undo get. set.
    define public property ListePorteLotsoS                  as character no-undo get. set.
    define public property ListePUoS                         as character no-undo get. set.
    define public property ListeQteoS                        as character no-undo get. set.
    define public property ListeRefarticleoS                 as character no-undo get. set.
    define public property ListeRubArtOs                     as character no-undo get. set.
    define public property ListeSSRubArtOs                   as character no-undo get. set.
    define public property ListePortableOccupantLotsOS       as character no-undo get. set.
    define public property ListeTeloccupantLotsoS            as character no-undo get. set.
    define public property ListeTVaoS                        as character no-undo get. set.
    define public property ListeTxRemiseoS                   as character no-undo get. set.
    define public property ListeTxTVaoS                      as character no-undo get. set.
    define public property MotifClotureOS                    as character no-undo get. set.
    define public property NomSignalantOS                    as character no-undo get. set.
    define public property NomCompletSignalantOS             as character no-undo get. set.
    define public property NumDossierTravOs                  as character no-undo get. set.
    define public property NumFourniordreService             as character no-undo get. set.
    define public property NumordreService                   as character no-undo get. set.
    define public property PortableSignalantoS               as character no-undo get. set.
    define public property RoleSignalantOS                   as character no-undo get. set.
    define public property SuiteadresseSignalantOS           as character no-undo get. set.
    define public property TableordreService                 as character no-undo get. set.
    define public property TableLotsoS                       as character no-undo get. set.
    define public property TableLotsoccupantsOS              as character no-undo get. set.
    define public property TauxTVareduitoS                   as character no-undo get. set.
    define public property TelSignalantOS                    as character no-undo get. set.
    define public property TitreSignalantOS                  as character no-undo get. set.
    define public property TitreLSignalantOS                 as character no-undo get. set.
    define public property TotalTTCOS                        as character no-undo get. set.
    define public property TotalHTOS                         as character no-undo get. set.
    define public property TotalTVAOS                        as character no-undo get. set.
    define public property UtilisateurCreationOS             as character no-undo get. set.
    define public property VilleSignalantOS                  as character no-undo get. set.
    define public property VilleCedexSignalantOS             as character no-undo get. set.
    
    
end class.
