/*------------------------------------------------------------------------
File        : fusionEvenement.cls
Purpose     : Classe des champs fusion utilisateur EVENEMENT
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
block-level on error undo, throw.
class bureautique.fusion.classe.fusionEvenement:
    /*------------------------------------------------------------------------------
    purpose:
    Notes  :
    ------------------------------------------------------------------------------*/
    define public property Dossierevenement as character no-undo get. set.
    define public property objetevenement   as character no-undo get. set.
end class.
