/*------------------------------------------------------------------------
File        : fusionAssurance.i
Purpose     : Variables préprocesseur des champs fusion utilisateur ASSURANCE
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
&GLOBAL-DEFINE FUSION-TitreCompagnie           "104366"
&GLOBAL-DEFINE FUSION-NomCompagnie             "104367"
&GLOBAL-DEFINE FUSION-adresseCompagnie         "104368"
&GLOBAL-DEFINE FUSION-SuiteadresseCompagnie    "104369"
&GLOBAL-DEFINE FUSION-VilleCompagnie           "104370"
&GLOBAL-DEFINE FUSION-CodePostalCompagnie      "104371"
&GLOBAL-DEFINE FUSION-NumPoliceassurance       "104372"
&GLOBAL-DEFINE FUSION-DateDbtassurance         "104373"
&GLOBAL-DEFINE FUSION-DateFinassurance         "104374"
&GLOBAL-DEFINE FUSION-TitreCourtier            "104375"
&GLOBAL-DEFINE FUSION-NomCourtier              "104376"
&GLOBAL-DEFINE FUSION-adresseCourtier          "104377"
&GLOBAL-DEFINE FUSION-SuiteadresseCourtier     "104378"
&GLOBAL-DEFINE FUSION-VilleCourtier            "104379"
&GLOBAL-DEFINE FUSION-CodePostalCourtier       "104380"
&GLOBAL-DEFINE FUSION-LstGarassurance          "104769"
&GLOBAL-DEFINE FUSION-DatelDbtassurance        "108323"
&GLOBAL-DEFINE FUSION-DateDbtassuranceLettre   "108324"
&GLOBAL-DEFINE FUSION-DatelFinassurance        "108325"
&GLOBAL-DEFINE FUSION-DateFinassuranceLettre   "108326"
&GLOBAL-DEFINE FUSION-DateSigassurance         "110452"
&GLOBAL-DEFINE FUSION-DateLSigassurance        "110453"
&GLOBAL-DEFINE FUSION-DateSigassuranceenLettre "110454"
&GLOBAL-DEFINE FUSION-DateIniassurance         "110455"
&GLOBAL-DEFINE FUSION-DateLIniassurance        "110456"
&GLOBAL-DEFINE FUSION-DateIniassuranceenLettre "110457"
&GLOBAL-DEFINE FUSION-VilleCedexCompagnie      "110812"
&GLOBAL-DEFINE FUSION-VilleCedexCourtier       "110813"
&GLOBAL-DEFINE FUSION-emailCompagnie           "111251"
&GLOBAL-DEFINE FUSION-TelephoneCompagnie       "111252"
&GLOBAL-DEFINE FUSION-FaxCompagnie             "111253"
&GLOBAL-DEFINE FUSION-emailCourtier            "111254"
&GLOBAL-DEFINE FUSION-TelephoneCourtier        "111255"
&GLOBAL-DEFINE FUSION-FaxCourtier              "111256"
&GLOBAL-DEFINE FUSION-ComplementAdresseIdentCompagnie "111606"
&GLOBAL-DEFINE FUSION-ComplementAdresseIdentCourtier  "111609"
