/*------------------------------------------------------------------------
File        : fusionDevis.i
Purpose     : Variables préprocesseur des champs fusion utilisateur DEVIS
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
&GLOBAL-DEFINE FUSION-NumDevis                   "107798"
&GLOBAL-DEFINE FUSION-DateCreationDevis          "107799"
&GLOBAL-DEFINE FUSION-DateLCreationDevis         "107800"
&GLOBAL-DEFINE FUSION-NumFourniDevis             "107801"
&GLOBAL-DEFINE FUSION-TableDevis                 "107802"
&GLOBAL-DEFINE FUSION-DelaiDevis                 "107803"
&GLOBAL-DEFINE FUSION-CondPaiemDevis             "107935"
&GLOBAL-DEFINE FUSION-CondPortDevis              "107936"
&GLOBAL-DEFINE FUSION-DateCreationDevisLettre    "108304"
&GLOBAL-DEFINE FUSION-ListeDesignationDevis      "110241"
&GLOBAL-DEFINE FUSION-ListeRefarticleDevis       "110242"
&GLOBAL-DEFINE FUSION-ListeQteDevis              "110243"
&GLOBAL-DEFINE FUSION-ListeDelaiDevis            "110244"
&GLOBAL-DEFINE FUSION-ListeCommentaireDevis      "110245"
&GLOBAL-DEFINE FUSION-ListePUDevis               "110268"
&GLOBAL-DEFINE FUSION-ListeTxRemiseDevis         "110269"
&GLOBAL-DEFINE FUSION-ListeMontantDevis          "110270"
&GLOBAL-DEFINE FUSION-ListeCleDevis              "110598"
&GLOBAL-DEFINE FUSION-ListeCleLibelleDevis       "110601"
&GLOBAL-DEFINE FUSION-ListeLotsDevis             "110936"
&GLOBAL-DEFINE FUSION-ListeNatureLotsDevis       "110937"
&GLOBAL-DEFINE FUSION-ListeBatLotsDevis          "110938"
&GLOBAL-DEFINE FUSION-ListeentreeLotsDevis       "110939"
&GLOBAL-DEFINE FUSION-ListeescLotsDevis          "110940"
&GLOBAL-DEFINE FUSION-ListeetageLotsDevis        "110941"
&GLOBAL-DEFINE FUSION-ListePorteLotsDevis        "110942"
&GLOBAL-DEFINE FUSION-ListeoccupantLotsDevis     "110943"
&GLOBAL-DEFINE FUSION-TableLotsDevis             "110944"
&GLOBAL-DEFINE FUSION-TableLotsoccupantsDevis    "110945"
&GLOBAL-DEFINE FUSION-RoleSignalantDevis         "110967"
&GLOBAL-DEFINE FUSION-TitreSignalantDevis        "110968"
&GLOBAL-DEFINE FUSION-TitreLSignalantDevis       "110969"
&GLOBAL-DEFINE FUSION-CiviliteSignalantDevis     "110970"
&GLOBAL-DEFINE FUSION-NomSignalantDevis          "110971"
&GLOBAL-DEFINE FUSION-NomCompletSignalantDevis   "110972"
&GLOBAL-DEFINE FUSION-adresseSignalantDevis      "110973"
&GLOBAL-DEFINE FUSION-SuiteadresseSignalantDevis "110974"
&GLOBAL-DEFINE FUSION-CodePostalSignalantDevis   "110975"
&GLOBAL-DEFINE FUSION-VilleSignalantDevis        "110976"
&GLOBAL-DEFINE FUSION-VilleCedexSignalantDevis   "110977"
&GLOBAL-DEFINE FUSION-ListeTeloccupantLotsDevis  "110990"
&GLOBAL-DEFINE FUSION-TelSignalantDevis          "111084"
&GLOBAL-DEFINE FUSION-PortableSignalantDevis     "111085"
&GLOBAL-DEFINE FUSION-ListeemailoccupantDevis    "111525"
