/*------------------------------------------------------------------------
File        : fusionDocument.i
Purpose     : Variables préprocesseur des champs fusion utilisateur DOCUMENT
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
&GLOBAL-DEFINE FUSION-SignataireCourrierBis          "104260"
&GLOBAL-DEFINE FUSION-entete                         "104756"
&GLOBAL-DEFINE FUSION-PiedPage                       "104757"
&GLOBAL-DEFINE FUSION-TelSignataire1                 "105701"
&GLOBAL-DEFINE FUSION-TelSignataire2                 "105702"
&GLOBAL-DEFINE FUSION-DateCreationSousDossier        "106059"
&GLOBAL-DEFINE FUSION-DateFinSousDossier             "106060"
&GLOBAL-DEFINE FUSION-DateCreationCourrier           "106061"
&GLOBAL-DEFINE FUSION-DateeditionCourrier            "106062"
&GLOBAL-DEFINE FUSION-DateRelanceCourrier            "106063"
&GLOBAL-DEFINE FUSION-DateFinCourrier                "106064"
&GLOBAL-DEFINE FUSION-DateemailCourrier              "106065"
&GLOBAL-DEFINE FUSION-DateFaxCourrier                "106066"
&GLOBAL-DEFINE FUSION-ReferenceCourrier              "106067"
&GLOBAL-DEFINE FUSION-NumaR                          "106068"
&GLOBAL-DEFINE FUSION-FonctionSignataire1            "106069"
&GLOBAL-DEFINE FUSION-FonctionSignataire2            "106070"
&GLOBAL-DEFINE FUSION-DateLCreationSousDossier       "107271"
&GLOBAL-DEFINE FUSION-DateLFinSousDossier            "107272"
&GLOBAL-DEFINE FUSION-DateLCreationCourrier          "107273"
&GLOBAL-DEFINE FUSION-DateLeditionCourrier           "107274"
&GLOBAL-DEFINE FUSION-DateLRelanceCourrier           "107275"
&GLOBAL-DEFINE FUSION-DateLFinCourrier               "107276"
&GLOBAL-DEFINE FUSION-DateLemailCourrier             "107277"
&GLOBAL-DEFINE FUSION-DateLFaxCourrier               "107278"
&GLOBAL-DEFINE FUSION-DateCreationCourrierLettre     "107920"
&GLOBAL-DEFINE FUSION-DateeditionCourrierLettre      "108310"
&GLOBAL-DEFINE FUSION-DateRelanceCourrierLettre      "108311"
&GLOBAL-DEFINE FUSION-DateFinCourrierLettre          "108312"
&GLOBAL-DEFINE FUSION-DateemailCourrierLettre        "108313"
&GLOBAL-DEFINE FUSION-DateFaxCourrierLettre          "108314"
&GLOBAL-DEFINE FUSION-DateCreationSousDossierLettre  "108315"
&GLOBAL-DEFINE FUSION-DateFinSousDossierLettre       "108316"
&GLOBAL-DEFINE FUSION-InitialesSignataireCourrier    "110466"
&GLOBAL-DEFINE FUSION-InitialesSignataireCourrierBis "110467"
&GLOBAL-DEFINE FUSION-PortableSignataire             "110564"
&GLOBAL-DEFINE FUSION-PortableSignataireBis          "110565"
&GLOBAL-DEFINE FUSION-FaxSignataire                  "110570"
&GLOBAL-DEFINE FUSION-FaxSignataireBis               "110571"
&GLOBAL-DEFINE FUSION-emailSignataire                "110581"
&GLOBAL-DEFINE FUSION-emailSignataireBis             "110582"
&GLOBAL-DEFINE FUSION-cheminlogo                     "172"
&GLOBAL-DEFINE FUSION-SignataireCourrier             "215"
&GLOBAL-DEFINE FUSION-CommentaireTechnique           "216"
&GLOBAL-DEFINE FUSION-CommentaireFinancier           "217"
