/*------------------------------------------------------------------------
File        : fusionOrganismesocial.i
Purpose     : Variables préprocesseur des champs fusion utilisateur ORGANISMESOCIAL
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
&GLOBAL-DEFINE FUSION-TitreCaF                   "105511"
&GLOBAL-DEFINE FUSION-TitreLCaF                  "105512"
&GLOBAL-DEFINE FUSION-NomCaF                     "105513"
&GLOBAL-DEFINE FUSION-adresseCaF                 "105514"
&GLOBAL-DEFINE FUSION-SuiteadresseCaF            "105515"
&GLOBAL-DEFINE FUSION-CodePostalCaF              "105516"
&GLOBAL-DEFINE FUSION-VilleCaF                   "105517"
&GLOBAL-DEFINE FUSION-TitreCentrePaiement        "105518"
&GLOBAL-DEFINE FUSION-TitreLCentrePaiement       "105519"
&GLOBAL-DEFINE FUSION-NomCentrePaiement          "105520"
&GLOBAL-DEFINE FUSION-adresseCentrePaiement      "105521"
&GLOBAL-DEFINE FUSION-SuiteadresseCentrePaiement "105522"
&GLOBAL-DEFINE FUSION-CodePostalCentrePaiement   "105523"
&GLOBAL-DEFINE FUSION-VilleCentrePaiement        "105524"
&GLOBAL-DEFINE FUSION-TitreCentreRecette         "105525"
&GLOBAL-DEFINE FUSION-TitreLCentreRecette        "105526"
&GLOBAL-DEFINE FUSION-NomCentreRecette           "105527"
&GLOBAL-DEFINE FUSION-adresseCentreRecette       "105528"
&GLOBAL-DEFINE FUSION-SuiteadresseCentreRecette  "105529"
&GLOBAL-DEFINE FUSION-CodePostalCentreRecette    "105530"
&GLOBAL-DEFINE FUSION-VilleCentreRecette         "105531"
&GLOBAL-DEFINE FUSION-TitreaSSeDIC               "105546"
&GLOBAL-DEFINE FUSION-TitreLaSSeDIC              "105547"
&GLOBAL-DEFINE FUSION-NomaSSeDIC                 "105548"
&GLOBAL-DEFINE FUSION-adresseaSSeDIC             "105549"
&GLOBAL-DEFINE FUSION-SuiteadresseaSSeDIC        "105550"
&GLOBAL-DEFINE FUSION-CodePostalaSSeDIC          "105551"
&GLOBAL-DEFINE FUSION-VilleaSSeDIC               "105552"
&GLOBAL-DEFINE FUSION-adresseCentreImpot         "106143"
&GLOBAL-DEFINE FUSION-SuiteadresseCentreImpot    "106144"
&GLOBAL-DEFINE FUSION-CodePostalCentreImpot      "106145"
&GLOBAL-DEFINE FUSION-VilleCentreImpot           "106146"
&GLOBAL-DEFINE FUSION-NomCentreImpot             "106147"
&GLOBAL-DEFINE FUSION-TelephoneCentreImpot       "106148"
&GLOBAL-DEFINE FUSION-TelephoneCentreImpot       "107769"
&GLOBAL-DEFINE FUSION-VilleCedexCaF              "110821"
&GLOBAL-DEFINE FUSION-VilleCedexCentrePaiement   "110822"
&GLOBAL-DEFINE FUSION-VilleCedexCentreRecette    "110823"
&GLOBAL-DEFINE FUSION-VilleCedexaSSeDIC          "110824"
&GLOBAL-DEFINE FUSION-VilleCedexacheteurDoMut    "110827"
