/*------------------------------------------------------------------------
File        : fusionSignalement.i
Purpose     : Variables préprocesseur des champs fusion utilisateur SIGNALEMENT
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
&GLOBAL-DEFINE FUSION-NumSignalement                   "107795"
&GLOBAL-DEFINE FUSION-DelaiSignalement                 "107796"
&GLOBAL-DEFINE FUSION-TableSignalement                 "107797"
&GLOBAL-DEFINE FUSION-TableComplInfo                   "107948"
&GLOBAL-DEFINE FUSION-ListeDesignationSignalement      "110236"
&GLOBAL-DEFINE FUSION-ListeRefarticleSignalement       "110237"
&GLOBAL-DEFINE FUSION-ListeQteSignalement              "110238"
&GLOBAL-DEFINE FUSION-ListeDelaiSignalement            "110239"
&GLOBAL-DEFINE FUSION-ListeCommentaireSignalement      "110240"
&GLOBAL-DEFINE FUSION-ListeCleSignalement              "110597"
&GLOBAL-DEFINE FUSION-ListeCleLibelleSignalement       "110600"
&GLOBAL-DEFINE FUSION-ListeLotsSignalement             "110946"
&GLOBAL-DEFINE FUSION-ListeNatureLotsSignalement       "110947"
&GLOBAL-DEFINE FUSION-ListeBatLotsSignalement          "110948"
&GLOBAL-DEFINE FUSION-ListeentreeLotsSignalement       "110949"
&GLOBAL-DEFINE FUSION-ListeescLotsSignalement          "110950"
&GLOBAL-DEFINE FUSION-ListeetageLotsSignalement        "110951"
&GLOBAL-DEFINE FUSION-ListePorteLotsSignalement        "110952"
&GLOBAL-DEFINE FUSION-ListeoccupantLotsSignalement     "110953"
&GLOBAL-DEFINE FUSION-TableLotsSignalement             "110954"
&GLOBAL-DEFINE FUSION-TableLotsoccupantsSignalement    "110955"
&GLOBAL-DEFINE FUSION-RoleSignalantSignalement         "110978"
&GLOBAL-DEFINE FUSION-TitreSignalantSignalement        "110979"
&GLOBAL-DEFINE FUSION-TitreLSignalantSignalement       "110980"
&GLOBAL-DEFINE FUSION-CiviliteSignalantSignalement     "110981"
&GLOBAL-DEFINE FUSION-NomSignalantSignalement          "110982"
&GLOBAL-DEFINE FUSION-NomCompletSignalantSignalement   "110983"
&GLOBAL-DEFINE FUSION-adresseSignalantSignalement      "110984"
&GLOBAL-DEFINE FUSION-SuiteadresseSignalantSignalement "110985"
&GLOBAL-DEFINE FUSION-CodePostalSignalantSignalement   "110986"
&GLOBAL-DEFINE FUSION-VilleSignalantSignalement        "110987"
&GLOBAL-DEFINE FUSION-VilleCedexSignalantSignalement   "110988"
&GLOBAL-DEFINE FUSION-ListeTeloccupantLotsSignalement  "110991"
&GLOBAL-DEFINE FUSION-TelSignalantSignalement          "111086"
&GLOBAL-DEFINE FUSION-PortableSignalantSignalement     "111087"
&GLOBAL-DEFINE FUSION-ListeRubartSignalement           "111421"
&GLOBAL-DEFINE FUSION-ListeSSRubartSignalement         "111422"
&GLOBAL-DEFINE FUSION-ListeCodeFiscartSignalement      "111423"
&GLOBAL-DEFINE FUSION-ListeRubartDevis                 "111424"
&GLOBAL-DEFINE FUSION-ListeSSRubartDevis               "111425"
&GLOBAL-DEFINE FUSION-ListeCodeFiscartDevis            "111426"
&GLOBAL-DEFINE FUSION-ListeRubartoS                    "111427"
&GLOBAL-DEFINE FUSION-ListeSSRubartoS                  "111428"
&GLOBAL-DEFINE FUSION-ListeCodeFiscartoS               "111429"
&GLOBAL-DEFINE FUSION-ListeemailoccupantSignalement    "111526"
