/*------------------------------------------------------------------------
File        : fusionGeneral.i
Purpose     : Variables préprocesseur des champs fusion utilisateur GENERAL
Author(s)   : Génération automatique le 2018/01/25
Notes       :
------------------------------------------------------------------------*/
&GLOBAL-DEFINE FUSION-TelephoneCabinet               "104299"
&GLOBAL-DEFINE FUSION-NoCompteBancaireCabinet        "105855"
&GLOBAL-DEFINE FUSION-DatelobtentionCarte            "108269"
&GLOBAL-DEFINE FUSION-DateobtentionCarteLettre       "108270"
&GLOBAL-DEFINE FUSION-FaxCabinet                     "110357"
&GLOBAL-DEFINE FUSION-PaysGarant                     "110415"
&GLOBAL-DEFINE FUSION-emailCabinet                   "110580"
&GLOBAL-DEFINE FUSION-VilleCedex_cabinet             "110818"
&GLOBAL-DEFINE FUSION-NoBICCabinet                   "111098"
&GLOBAL-DEFINE FUSION-DatePassagePrelSePaCopropriete "111257"
&GLOBAL-DEFINE FUSION-DelaiNotifPrelSePaCopropriete  "111258"
&GLOBAL-DEFINE FUSION-NomReclamPrelSePaCopropriete   "111259"
&GLOBAL-DEFINE FUSION-NomModifPrelSePaCopropriete    "111260"
&GLOBAL-DEFINE FUSION-DatePassagePrelSePaGerance     "111261"
&GLOBAL-DEFINE FUSION-DelaiNotifPrelSePaGerance      "111262"
&GLOBAL-DEFINE FUSION-NomReclamPrelSePaGerance       "111263"
&GLOBAL-DEFINE FUSION-NomModifPrelSePaGerance        "111264"
&GLOBAL-DEFINE FUSION-ComplementAdresseIdent_Cabinet "111635"
&GLOBAL-DEFINE FUSION-Titre_cabinet                  "52"
&GLOBAL-DEFINE FUSION-Nom_Cabinet                    "53"
&GLOBAL-DEFINE FUSION-Adresse_cabinet                "58"
&GLOBAL-DEFINE FUSION-Suite_adresse_cabinet          "59"
&GLOBAL-DEFINE FUSION-Code_postal_cabinet            "60"
&GLOBAL-DEFINE FUSION-Ville_cabinet                  "61"
&GLOBAL-DEFINE FUSION-Numero_Carte_Prof              "62"
&GLOBAL-DEFINE FUSION-Date_obtention_carte           "63"
&GLOBAL-DEFINE FUSION-Lieu_obtention_carte           "64"
&GLOBAL-DEFINE FUSION-Syndicat_professionnel         "73"
&GLOBAL-DEFINE FUSION-DescriptionGarant              "82"
&GLOBAL-DEFINE FUSION-Gerant_Cabinet                 "86"
&GLOBAL-DEFINE FUSION-Banque_cabinet                 "87"
&GLOBAL-DEFINE FUSION-Honoraire_cabinet              "88"
&GLOBAL-DEFINE FUSION-Honoraire_cabinetenlettre      "89"
